%YAML:1.0

# Number of superpixels

superpixelNum: 1000

# Stereo processing

stereo: 1

# Weights for energy terms in Equations (1), (7), (9), (10) from the paper
# Values below give best results on kitti database

appWeight: 200.0
regWeight: 500.0
lenWeight: 1000.0
sizeWeight: 1000.0
dispWeight: 3000.0
smoWeight: 200
priorWeight: 0.2
occPriorWeight: 15
hiPriorWeight: 0.7 
reSteps: 4
minPixelSize: 3
