%YAML:1.0

# pixel/superpixel size
pixelSize: 7
sPixelSize: 3

stereo: 1
iterations: 1
reSteps: [4, 4, 4, 4]
minLevel: 2

# energy weights
appWeight: [200.0, 200.0, 200.0, 200.0]
regWeight: [200.0, 200.0, 200.0, 500.0]
lenWeight: 1000.0
sizeWeight: 1000.0
dispWeight: [6000.0, 5000.0, 3000.0, 3000.0]
smoWeight: [500, 500, 200, 200]
priorWeight: 0.2
occPriorWeight: [15, 15, 15, 15]
hiPriorWeight: [0.5, 0.5, 0.7, 0.7] 
inlierThreshold: 3
peblThreshold: [2, 2, 2, 2]
updateThreshold: 0.01
instantBoundary: 0
