%YAML:1.0

# Number of superpixels

superpixelNum: 1000

# Stereo processing

stereo: 1
batchProcessing: 0

# Weights for energy terms in Equations (1), (7), (9), (10) from the paper
# Values below give best results on kitti database

appWeight: 100.0
regWeight: 0.0
lenWeight: 1000.0
sizeWeight: 1000.0
dispWeight: 3000.0
smoWeightCo: 0.2
smoWeightHi: 0.2
priorWeight: 1
occPriorWeight: 15
hiPriorWeight: 2
inlierThreshold: 3
updateThreshold: 0.01
minPixelSize: 3
